/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Component: typeof import('./components/component/component.vue')['default']
    ComponentA: typeof import('./components/component/component-a.vue')['default']
    ComponentB: typeof import('./components/component/component-b.vue')['default']
    CursorPositon: typeof import('./components/slot/cursor-positon.vue')['default']
    DefaultSlot: typeof import('./components/slot/default-slot.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NameSlot: typeof import('./components/slot/name-slot.vue')['default']
    ScopeNameSlot: typeof import('./components/slot/scope-name-slot.vue')['default']
    TabContolContent: typeof import('./base-ui/tab-control/tab-contol-content.vue')['default']
    TabControl: typeof import('./base-ui/tab-control/index.vue')['default']
    TabControlItem: typeof import('./base-ui/tab-control/tab-control-item.vue')['default']
  }
}
